# Example ItemConfig.yml
# Do not forget to turn the YAML file on in the settings.

# Predefined groups:
# all, ore, metal, food, potions, woods, trophy, boss trophy, valuable, seed, crop, stackable.
# pants, chest, helmet, cape, armor.
# axes, clubs, knives, pickaxes, polearms, spears, swords, bows, crossbows, weapon, arrows, bolts, ammo.
# round shield, tower shield, shield.
# special (fishing rod and megingjord), tool, equipment.

# Things you can change: amount, weight, weight factor, stack, stack factor, pickup, floating, teleportable, loss.
# Things you can configure per world level: amount, pickup, teleportable, loss.

# Note: If you are using mods that create custom items / prefabs, you might need to add and configure them
#       explicitly by creating your own groups for those. Predefined groups only contain Valheim's original
#       items. 

# Define your own groups here and assign items via display name (or the internal ID) to your groups.
# Hint: If you want to find the internal ID of an item, you can look it up in the wiki.
# https://valheim.fandom.com
# For custom items, please refer to the documentation of the mod that adds them.
#
# groups:
#   My Group:
#      - Display Name
#      - InternalID

# Examples:
# groups:
#   Huge Wood Gain:
#     - Wood
#     - Fine Wood
#     - Core Wood
#     - Ancient Bark

wood:
  amount: 1.5

RoundLog:
  amount: 1.5

Stone:
  amount: 2

all:
  loss:
    0: no
    1: default