MeadowsLoot1:
  - Flint
  - Feathers
  - Raspberry
  - BCA_ChiliPepperSeeds
  - BCA_TomatoSeeds
MeadowsLoot2:
  - Flint
  - Feathers
  - LeatherScraps
  - DeerHide
  - BCA_ChiliPepperSeeds
  - BCA_TomatoSeeds
MeadowsLoot3:
  - FineWood
  - Bronze
  - CopperOre
  - DeerHide
  - BCA_ChiliPepperSeeds
  - BCA_TomatoSeeds