- prefab: instanced_waterlilies
  amount: 40
  biome: PrimevalForest
  instanced: true
  scaleMin: 0.4
  scaleMax: 0.6
  maxTilt: 90
  minAltitude: -1.5
  maxAltitude: -0.2
  snapToWater: true
  randomOffset: 0.1
  maxOceanDepth: 1
  fractalScale: 2
- prefab: instanced_vass
  amount: 30
  biome: PrimevalForest
  instanced: true
  scaleMin: 1.2
  scaleMax: 1.5
  maxTilt: 90
  minAltitude: -1.5
  maxAltitude: -0.1
  snapToWater: true
  fractalScale: 5
- prefab: instanced_swamp_grass
  amount: 80
  biome: PrimevalForest
  instanced: true
  scaleMin: 1.65
  maxTilt: 50
  minAltitude: 0
  maxAltitude: 1000
  terrainTilt: true
  fractalThresholdMin: 0.5
- prefab: instanced_shrub
  amount: 7
  biome: PrimevalForest
  instanced: true
  scaleMax: 1.25
  maxTilt: 50
  minAltitude: 1
  maxAltitude: 1000
  fractalThresholdMin: 0.5
- prefab: instanced_meadows_grass_short
  amount: 80
  biome: PrimevalForest
  instanced: true
  scaleMin: 0.7
  scaleMax: 1.1
  maxTilt: 50
  minAltitude: 0.3
  maxAltitude: 1000
  terrainTilt: true
  fractalScale: 3
  fractalThresholdMin: 0.5
  fractalThresholdMax: 2.25
- prefab: instanced_ormbunke
  amount: 35
  biome: PrimevalForest
  instanced: true
  scaleMin: 1.2
  scaleMax: 1.35
  maxTilt: 24
  minAltitude: 1
  maxAltitude: 1000
  terrainTilt: true
  fractalThresholdMin: 0.5