- prefab: Runestone_GreydwarfElderTG
  biome: Meadows
  quantity: 4
  maxDistance: 1
  minAltitude: 0
  maxAltitude: 100
  prioritized: true
  group: Runestone_GreydwarfElderTG
  minDistanceFromSimilar: 100
  randomRotation: true
  maxTerrainDelta: 2
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 20
  clearArea: true
  noBuild: true
- prefab: Runestone_TrollWarriorTG
  biome: BlackForest
  quantity: 4
  maxDistance: 1
  minAltitude: 0
  maxAltitude: 100
  prioritized: true
  group: Runestone_TrollWarriorTG
  minDistanceFromSimilar: 100
  randomRotation: true
  maxTerrainDelta: 2
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 20
  clearArea: true
  noBuild: true
- prefab: Runestone_WhisperTG
  biome: Swamp
  quantity: 4
  maxDistance: 1
  minAltitude: 0
  maxAltitude: 100
  prioritized: true
  group: Runestone_WhisperTG
  minDistanceFromSimilar: 100
  randomRotation: true
  maxTerrainDelta: 2
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 20
  clearArea: true
  noBuild: true
- prefab: Runestone_LightningWolfTG
  biome: Mountain
  quantity: 4
  maxDistance: 1
  minAltitude: 10
  maxAltitude: 100
  prioritized: true
  group: Runestone_LightningWolfTG
  minDistanceFromSimilar: 100
  randomRotation: true
  maxTerrainDelta: 2
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 20
  clearArea: true
  noBuild: true
- prefab: Runestone_QueenDeathsquitoTG
  biome: Plains
  quantity: 4
  maxDistance: 1
  minAltitude: 0
  maxAltitude: 100
  prioritized: true
  group: Runestone_QueenDeathsquitoTG
  minDistanceFromSimilar: 100
  randomRotation: true
  maxTerrainDelta: 2
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 20
  clearArea: true
  noBuild: true
