- prefab: InfestedTree01:Prime
  biome: PrimevalForest
  biomeArea: median
  quantity: 150
  minAltitude: -1
  randomRotation: true
  maxTerrainDelta: 3
  exteriorRadius: 10
  randomDamage: true
- prefab: SwampHut1:Prime
  biome: PrimevalForest
  quantity: 60
  minAltitude: -2
  group: Swamphut
  minDistanceFromSimilar: 128
  randomRotation: true
  maxTerrainDelta: 3
  exteriorRadius: 8
  randomDamage: true
- prefab: SwampHut2:Prime
  biome: PrimevalForest
  quantity: 60
  minAltitude: 2
  group: Swamphut
  minDistanceFromSimilar: 128
  randomRotation: true
  maxTerrainDelta: 3
  exteriorRadius: 8
  randomDamage: true
- prefab: SwampHut3:Prime
  biome: PrimevalForest
  quantity: 60
  minAltitude: 2
  group: Swamphut
  minDistanceFromSimilar: 128
  randomRotation: true
  maxTerrainDelta: 3
  exteriorRadius: 8
  randomDamage: true
- prefab: SwampHut5:Prime
  biome: PrimevalForest
  quantity: 85
  minAltitude: -1
  group: Swamphut
  minDistanceFromSimilar: 128
  randomRotation: true
  maxTerrainDelta: 3
  exteriorRadius: 10
  clearArea: true
  randomDamage: true
- prefab: MountainGrave01:Prime
  biome: PrimevalForest
  quantity: 200
  minAltitude: 10
  minDistanceFromSimilar: 50
  randomRotation: true
  maxTerrainDelta: 2
  exteriorRadius: 10
  clearArea: true