- prefab: ShipWreck01:Coast
  biome: RockyCoast
  quantity: 60
  minAltitude: 0
  maxAltitude: 5
  group: Shipwreck
  minDistanceFromSimilar: 250
  randomRotation: true
  exteriorRadius: 5
  clearArea: true
- prefab: ShipWreck02:Coast
  biome: RockyCoast
  quantity: 60
  minAltitude: 0
  maxAltitude: 5
  group: Shipwreck
  minDistanceFromSimilar: 250
  randomRotation: true
  exteriorRadius: 5
  clearArea: true
- prefab: ShipWreck03:Coast
  biome: RockyCoast
  quantity: 60
  minAltitude: 0
  maxAltitude: 5
  group: Shipwreck
  minDistanceFromSimilar: 250
  randomRotation: true
  exteriorRadius: 5
  clearArea: true
- prefab: ShipWreck04:Coast
  biome: RockyCoast
  quantity: 60
  minAltitude: 0
  maxAltitude: 5
  group: Shipwreck
  minDistanceFromSimilar: 250
  randomRotation: true
  exteriorRadius: 7
  clearArea: true