- prefab: MWL_Ruins1
  biome: Meadows
  quantity: 5
  maxDistance: 0.05
  minAltitude: 1
  prioritized: true
  group: Ruins_small
  minDistanceFromSimilar: 256
  maxTerrainDelta: 2
  exteriorRadius: 5
  clearArea: true
- prefab: MWL_Ruins2
  biome: Meadows
  quantity: 10
  minDistance: 0.05
  maxDistance: 0.2
  minAltitude: 1
  prioritized: true
  group: Ruins_medium
  minDistanceFromSimilar: 512
  discoverLabel: Hjortkult Ruins
  maxTerrainDelta: 3
  exteriorRadius: 8
  clearArea: true
  randomDamage: true
- prefab: MWL_Ruins3
  biome: Meadows
  quantity: 25
  maxDistance: 0.05
  minAltitude: 1
  prioritized: true
  group: Ruins_small
  minDistanceFromSimilar: 256
  discoverLabel: Hjortkult Ruins
  maxTerrainDelta: 3
  exteriorRadius: 7
  clearArea: true
  randomDamage: true
- prefab: MWL_Ruins6
  biome: Meadows
  quantity: 5
  minDistance: 0.15
  maxDistance: 0.3
  minAltitude: 1
  prioritized: true
  group: Ruins_small
  minDistanceFromSimilar: 256
  maxTerrainDelta: 3
  exteriorRadius: 14
  randomDamage: true
- prefab: MWL_Ruins7
  biome: Meadows
  quantity: 2
  maxDistance: 0.05
  minAltitude: 1
  prioritized: true
  group: Ruins_medium
  minDistanceFromSimilar: 512
  maxTerrainDelta: 5
  exteriorRadius: 7
  randomDamage: true
- prefab: MWL_Ruins8
  biome: Meadows
  quantity: 5
  minDistance: 0.15
  maxDistance: 0.3
  minAltitude: 1
  prioritized: true
  group: Ruins_small
  minDistanceFromSimilar: 256
  maxTerrainDelta: 5
  exteriorRadius: 11
  randomDamage: true
- prefab: MWL_RuinsArena1
  biome: Meadows
  quantity: 25
  minDistance: 0.15
  maxDistance: 0.3
  minAltitude: 1
  prioritized: true
  group: Ruins_medium
  minDistanceFromSimilar: 512
  discoverLabel: Temple of Eik
  maxTerrainDelta: 3
  inForest: true
  forestTresholdMin: 1.2
  forestTresholdMax: 2
  exteriorRadius: 20
  clearArea: true
- prefab: MWL_RuinsArena3
  biome: Meadows
  quantity: 25
  minDistance: 0.05
  maxDistance: 0.2
  minAltitude: 1
  prioritized: true
  group: Ruins_small
  minDistanceFromSimilar: 512
  discoverLabel: Garden of Eik
  maxTerrainDelta: 3
  inForest: true
  exteriorRadius: 15
- prefab: MWL_RuinsChurch1
  biome: Meadows
  quantity: 25
  minDistance: 0.05
  maxDistance: 0.2
  minAltitude: 1
  prioritized: true
  group: Ruins_medium
  minDistanceFromSimilar: 256
  discoverLabel: Tyggrasons Church
  maxTerrainDelta: 3
  inForest: true
  forestTresholdMin: 1.2
  forestTresholdMax: 2
  exteriorRadius: 15
  randomDamage: true
- prefab: MWL_RuinsWell1
  biome: Meadows
  quantity: 5
  maxDistance: 0.05
  minAltitude: 1
  prioritized: true
  group: Ruins_small
  minDistanceFromSimilar: 256
  maxTerrainDelta: 2
  exteriorRadius: 7
  randomDamage: true
