- prefab: FirTree_oldLog
  min: 5
  max: 10
  scaleMax: 1.2
  chanceToUseGroundTilt: 1
  biome: PrimevalForest
  minAltitude: -1000
  maxAltitude: 1000
  maxTilt: 20
  maxTerrainDelta: 2
- prefab: Pickable_Branch
  min: 5
  max: 10
  chanceToUseGroundTilt: 1
  biome: PrimevalForest
  maxAltitude: 1000
  maxTerrainDelta: 2
- prefab: Pickable_Stone
  min: 10
  max: 21
  chanceToUseGroundTilt: 1
  biome: PrimevalForest
  maxAltitude: 1000
  minTilt: 22
  maxTerrainDelta: 2
  groupSizeMin: 2
  groupSizeMax: 3
  groupRadius: 2
- prefab: Beech_small1
  min: 2
  max: 8
  scaleMax: 1.5
  randTilt: 10
  biome: PrimevalForest
  minAltitude: 1
  maxAltitude: 1000
  maxTilt: 30
  maxTerrainDelta: 2
- prefab: Beech_small2
  min: 3
  max: 10
  scaleMax: 2
  randTilt: 10
  biome: PrimevalForest
  minAltitude: 1
  maxAltitude: 1000
  maxTilt: 30
  maxTerrainDelta: 2
- prefab: Rock_4
  max: 18
  scaleMax: 3
  biome: PrimevalForest
  minAltitude: -1000
  maxAltitude: 1000
  maxTerrainDelta: 2
- prefab: rock4_forest
  min: 2
  max: 5
  scaleMin: 0.8
  randTilt: 5
  biome: PrimevalForest
  minAltitude: 4
  maxAltitude: 1000
  minTilt: 5
  maxTilt: 45
  maxTerrainDelta: 2
  groundOffset: -2
- prefab: Rock_4
  min: 10
  max: 20
  scaleMax: 3
  chanceToUseGroundTilt: 1
  biome: PrimevalForest
  minAltitude: -1000
  maxAltitude: 1000
  maxTilt: 45
  maxTerrainDelta: 2
- prefab: Rock_3
  min: 5
  max: 12
  scaleMin: 3
  scaleMax: 6
  biome: PrimevalForest
  minAltitude: -1000
  maxAltitude: 1000
  maxTilt: 25
  maxTerrainDelta: 2
- prefab: Beech1
  min: 15
  max: 30
  scaleMin: 1.8
  scaleMax: 2.5
  randTilt: 4
  chanceToUseGroundTilt: 0.15
  biome: PrimevalForest
  minAltitude: 0.2
  maxAltitude: 1000
  maxOceanDepth: 2
  maxTilt: 30
  maxTerrainDelta: 2
- prefab: Birch1
  min: 3
  max: 8
  scaleMin: 1.5
  scaleMax: 3
  randTilt: 4
  chanceToUseGroundTilt: 0.15
  biome: PrimevalForest
  minAltitude: 0.2
  maxAltitude: 1000
  maxOceanDepth: 2
  maxTilt: 30
  maxTerrainDelta: 2
- prefab: Birch2
  max: 4
  scaleMin: 1.5
  scaleMax: 3
  randTilt: 4
  chanceToUseGroundTilt: 0.15
  biome: PrimevalForest
  minAltitude: 0.2
  maxAltitude: 1000
  maxOceanDepth: 2
  maxTilt: 30
  maxTerrainDelta: 2
- prefab: Oak1
  max: 3
  scaleMin: 1.5
  scaleMax: 3.5
  randTilt: 4
  biome: PrimevalForest
  biomeArea: median
  minAltitude: 0.5
  maxAltitude: 1000
  maxOceanDepth: 2
  maxTilt: 20
  maxTerrainDelta: 2
- prefab: FirTree
  min: 3
  max: 8
  scaleMin: 2.5
  scaleMax: 3.5
  randTilt: 4
  biome: PrimevalForest
  minAltitude: 0.1
  maxAltitude: 1000
  maxOceanDepth: 2
  maxTilt: 30
  maxTerrainDelta: 2
- prefab: FirTree
  min: 10
  max: 20
  scaleMin: 2
  scaleMax: 2.5
  randTilt: 4
  biome: PrimevalForest
  minAltitude: 0.1
  maxAltitude: 1000
  maxOceanDepth: 2
  maxTilt: 30
  maxTerrainDelta: 2
- prefab: Pinetree_01
  min: 20
  max: 40
  scaleMin: 2
  scaleMax: 4
  randTilt: 4
  chanceToUseGroundTilt: 0.1
  biome: PrimevalForest
  biomeArea: median
  minAltitude: 0.1
  maxAltitude: 1000
  maxOceanDepth: 1.5
  maxTilt: 30
  maxTerrainDelta: 2
- prefab: Bush02_en
  min: 2
  max: 6
  scaleMin: 1.5
  scaleMax: 2.25
  biome: PrimevalForest
  minAltitude: 1
  maxAltitude: 1000
  maxTilt: 30
  maxTerrainDelta: 2
  groupSizeMin: 5
  groupSizeMax: 15
  groupRadius: 15
- prefab: FirTree_small_dead
  min: 10
  max: 25
  scaleMin: 1.1
  scaleMax: 1.5
  randTilt: 5
  chanceToUseGroundTilt: 0.25
  biome: PrimevalForest
  minAltitude: 0.5
  maxAltitude: 1000
  maxTilt: 25
  maxTerrainDelta: 2
- prefab: SwampTree1
  min: 10
  max: 30
  scaleMin: 1.3
  scaleMax: 1.75
  randTilt: 10
  chanceToUseGroundTilt: 0.25
  biome: PrimevalForest
  minAltitude: -0.5
  maxAltitude: 1000
  maxOceanDepth: 2
  maxTilt: 30
  maxTerrainDelta: 2
- prefab: SwampTree2
  min: 2
  max: 6
  scaleMin: 1.35
  scaleMax: 1.75
  randTilt: 5
  chanceToUseGroundTilt: 0.15
  biome: PrimevalForest
  biomeArea: median
  minAltitude: -0.5
  maxAltitude: 1000
  maxOceanDepth: 2
  maxTilt: 35
  maxTerrainDelta: 2
- prefab: SwampTree2_log
  min: 1
  max: 3
  scaleMin: 1.5
  scaleMax: 2.5
  randTilt: 20
  biome: PrimevalForest
  biomeArea: median
  minAltitude: -0.5
  maxAltitude: 1000
  maxOceanDepth: 2
  maxTilt: 35
  maxTerrainDelta: 2
- prefab: stubbe
  min: 3
  max: 10
  scaleMin: 1.1
  scaleMax: 1.6
  chanceToUseGroundTilt: 1
  biome: PrimevalForest
  maxAltitude: 1000
  maxOceanDepth: 2
  maxTilt: 20
  maxTerrainDelta: 2
- prefab: stubbe
  min: 5
  max: 15
  scaleMax: 1.8
  chanceToUseGroundTilt: 1
  biome: PrimevalForest
  maxAltitude: 1000
  maxOceanDepth: 2
  maxTilt: 20
  maxTerrainDelta: 2
- prefab: stubbe
  min: 4
  max: 12
  scaleMin: 1.4
  scaleMax: 1.7
  chanceToUseGroundTilt: 1
  biome: PrimevalForest
  maxAltitude: 1000
  maxOceanDepth: 2
  maxTilt: 20
  maxTerrainDelta: 2
- prefab: Bush01
  min: 15
  max: 35
  scaleMax: 2
  biome: PrimevalForest
  minAltitude: 1
  maxAltitude: 1000
  maxTerrainDelta: 2
- prefab: Bush01_heath
  min: 7
  max: 20
  biome: PrimevalForest
  maxAltitude: 1000
  maxTerrainDelta: 2
- prefab: shrub_2_heath
  min: 10
  max: 20
  scaleMin: 1.5
  biome: PrimevalForest
  maxAltitude: 1000
  maxTerrainDelta: 2
- prefab: shrub_2_heath
  min: 7
  max: 18
  scaleMin: 1.35
  biome: PrimevalForest
  maxAltitude: 1000
  maxOceanDepth: 2
  maxTerrainDelta: 2
- prefab: Pickable_Thistle
  min: 4
  max: 8
  scaleMin: 1.3
  randTilt: 20
  biome: PrimevalForest
  biomeArea: median
  maxAltitude: 1000
  maxTilt: 20
  maxTerrainDelta: 2
  groupSizeMin: 2
  groupSizeMax: 5
  groupRadius: 4
- prefab: shrub_2
  min: 7
  max: 25
  scaleMin: 1.3
  biome: PrimevalForest
  minAltitude: 1
  maxAltitude: 1000
  maxTerrainDelta: 2
- prefab: Pickable_Mushroom
  min: 3
  max: 7
  scaleMax: 1.8
  biome: PrimevalForest
  minAltitude: 1
  maxAltitude: 1000
  maxOceanDepth: 2
  maxTilt: 25
  maxTerrainDelta: 2
  groupSizeMin: 3
  groupSizeMax: 6
  groupRadius: 5
- prefab: Pickable_Mushroom_yellow
  min: 4
  max: 8
  scaleMax: 1.8
  biome: PrimevalForest
  biomeArea: median
  minAltitude: 1
  maxAltitude: 1000
  maxOceanDepth: 2
  maxTilt: 25
  maxTerrainDelta: 2
  groupSizeMin: 3
  groupSizeMax: 6
  groupRadius: 5
- prefab: Pickable_Mushroom_blue
  min: 2
  max: 6
  scaleMax: 1.8
  biome: PrimevalForest
  biomeArea: median
  minAltitude: 1
  maxAltitude: 1000
  maxOceanDepth: 2
  maxTilt: 25
  maxTerrainDelta: 2
  groupSizeMin: 3
  groupSizeMax: 6
  groupRadius: 5
- prefab: RaspberryBush
  min: 3
  max: 6
  biome: PrimevalForest
  minAltitude: 1
  maxAltitude: 1000
  maxOceanDepth: 2
  maxTerrainDelta: 5
  groupSizeMax: 8
  groupRadius: 8
- prefab: BlueberryBush
  min: 2
  max: 5
  biome: PrimevalForest
  minAltitude: 1
  maxAltitude: 1000
  maxOceanDepth: 2
  maxTerrainDelta: 5
  groupSizeMax: 8
  groupRadius: 8
- prefab: Pickable_MountainRemains01_buried
  min: 1
  max: 1
  scaleMax: 1.5
  chanceToUseGroundTilt: 1
  biome: PrimevalForest
  minAltitude: 1
  maxAltitude: 1000
  maxTerrainDelta: 6
  snapToStaticSolid: true
  groupSizeMin: 0
  groupSizeMax: 1
  groupRadius: 5
- prefab: Pickable_ForestCryptRemains01
  min: 1
  max: 1
  scaleMax: 1.5
  chanceToUseGroundTilt: 1
  biome: PrimevalForest
  minAltitude: 1
  maxAltitude: 1000
  maxTerrainDelta: 6
  snapToStaticSolid: true
  groupSizeMin: 0
  groupSizeMax: 1
  groupRadius: 5
- prefab: Pickable_ForestCryptRemains02
  min: 1
  max: 1
  scaleMax: 1.5
  chanceToUseGroundTilt: 1
  biome: PrimevalForest
  minAltitude: 1
  maxAltitude: 1000
  maxTerrainDelta: 6
  snapToStaticSolid: true
  groupSizeMin: 0
  groupSizeMax: 1
  groupRadius: 5
- prefab: Pickable_ForestCryptRemains03
  min: 1
  max: 1
  scaleMax: 1.5
  chanceToUseGroundTilt: 1
  biome: PrimevalForest
  minAltitude: 1
  maxAltitude: 1000
  maxTerrainDelta: 6
  snapToStaticSolid: true
  groupSizeMin: 0
  groupSizeMax: 1
  groupRadius: 5
- prefab: Pickable_ForestCryptRemains04
  min: 1
  max: 1
  scaleMax: 1.5
  chanceToUseGroundTilt: 1
  biome: PrimevalForest
  minAltitude: 1
  maxAltitude: 1000
  maxTerrainDelta: 6
  snapToStaticSolid: true
  groupSizeMin: 0
  groupSizeMax: 1
  groupRadius: 5