- prefab: Fish1
  biome: PrimevalForest
  spawnChance: 50
  maxSpawned: 5
  spawnInterval: 120
  maxLevel: 5
  minAltitude: -3
  maxAltitude: -1.5
  spawnDistance: 20
  groupSizeMin: 2
  groupSizeMax: 6
  groupRadius: 2
  maxTilt: 99
  groundOffset: 0.1
  overrideLevelupChance: 20
- prefab: Fish2
  biome: PrimevalForest
  spawnChance: 50
  maxSpawned: 4
  spawnInterval: 120
  maxLevel: 5
  minAltitude: -5
  maxAltitude: -2
  spawnDistance: 20
  groupSizeMin: 2
  groupSizeMax: 4
  groupRadius: 2
  maxTilt: 99
  groundOffset: 0.1
  overrideLevelupChance: 20
- prefab: Fish5
  biome: PrimevalForest
  spawnChance: 50
  maxSpawned: 10
  spawnInterval: 80
  maxLevel: 5
  minAltitude: -999
  maxAltitude: -5
  spawnDistance: 12
  groupSizeMin: 3
  groupSizeMax: 7
  groupRadius: 2
  maxTilt: 99
  groundOffset: 0.1
  overrideLevelupChance: 20
- prefab: Fish6
  biome: PrimevalForest
  spawnChance: 60
  maxSpawned: 10
  spawnInterval: 80
  maxLevel: 5
  minAltitude: -999
  maxAltitude: -5
  spawnDistance: 10
  groupSizeMin: 3
  groupSizeMax: 7
  groupRadius: 2
  maxTilt: 99
  groundOffset: 0.1
  overrideLevelupChance: 20
- prefab: odin
  biome: PrimevalForest
  spawnChance: 10
  maxSpawned: 1
  spawnInterval: 3000
  minAltitude: 0
  maxAltitude: 1000
  spawnAtDay: false
  requiredGlobalKey: defeated_gdking
  spawnDistance: 10
  spawnRadiusMin: 35
  spawnRadiusMax: 35
  groupRadius: 3
- prefab: FireFlies
  biome: PrimevalForest
  spawnChance: 65
  maxSpawned: 7
  spawnInterval: 20
  minAltitude: 0
  maxAltitude: 1000
  spawnAtDay: false
  spawnDistance: 8
  groupRadius: 3
- prefab: Crow
  biome: PrimevalForest
  spawnChance: 5
  maxSpawned: 1
  spawnInterval: 360
  minAltitude: 0
  maxAltitude: 1000
  spawnDistance: 150
  groupSizeMax: 1
  groupRadius: 20
- prefab: Skeleton
  biome: PrimevalForest
  spawnChance: 30
  maxSpawned: 8
  spawnInterval: 350
  minLevel: 2
  maxLevel: 3
  minAltitude: -1
  maxAltitude: 1000
  spawnDistance: 15
  groupSizeMin: 3
  groupSizeMax: 5
  groupRadius: 4
  overrideLevelupChance: 75
- prefab: Skeleton_Poison
  biome: PrimevalForest
  spawnChance: 35
  maxSpawned: 2
  spawnInterval: 350
  maxLevel: 3
  minAltitude: -1
  maxAltitude: 1000
  spawnDistance: 15
  groupSizeMin: 1
  groupSizeMax: 2
  groupRadius: 4
  overrideLevelupChance: 85
- prefab: Skeleton_Poison
  biome: PrimevalForest
  spawnChance: 20
  maxSpawned: 1
  spawnInterval: 1000
  maxLevel: 3
  minAltitude: -1
  maxAltitude: 1000
  requiredEnvironments: PrimeDark, PrimeStorm, PrimeRain
  spawnDistance: 15
  groupSizeMin: 1
  groupSizeMax: 1
  groupRadius: 4
  overrideLevelupChance: 50
- prefab: Ghost
  biome: PrimevalForest
  spawnChance: 25
  maxSpawned: 3
  spawnInterval: 300
  minLevel: 2
  maxLevel: 3
  minAltitude: -1
  maxAltitude: 1000
  spawnDistance: 15
  groupSizeMin: 1
  groupSizeMax: 3
  groupRadius: 4
  overrideLevelupChance: 45
- prefab: Ghost
  biome: PrimevalForest
  spawnChance: 15
  maxSpawned: 2
  spawnInterval: 750
  minLevel: 2
  maxLevel: 3
  minAltitude: -1
  maxAltitude: 1000
  requiredEnvironments: PrimeDark, PrimeStorm
  spawnDistance: 15
  groupSizeMin: 1
  groupSizeMax: 2
  groupRadius: 4
  overrideLevelupChance: 20
- prefab: Wraith
  biome: PrimevalForest
  biomeArea: median
  spawnChance: 40
  maxSpawned: 2
  spawnInterval: 300
  minLevel: 1
  maxLevel: 3
  minAltitude: 1
  maxAltitude: 1000
  spawnDistance: 10
  groupRadius: 1
  maxTilt: 66
  groundOffset: 50
  overrideLevelupChance: 50
- prefab: Wraith
  biome: PrimevalForest
  biomeArea: median
  spawnChance: 25
  maxSpawned: 1
  spawnInterval: 1000
  minLevel: 2
  maxLevel: 3
  minAltitude: 1
  maxAltitude: 1000
  requiredEnvironments: PrimeDark, PrimeStorm
  spawnDistance: 10
  groupRadius: 1
  maxTilt: 66
  groundOffset: 50
  overrideLevelupChance: 25
- prefab: Surtling
  biome: PrimevalForest
  biomeArea: median
  spawnChance: 35
  maxSpawned: 3
  spawnInterval: 250
  maxLevel: 3
  minAltitude: -1
  maxAltitude: 1000
  spawnDistance: 15
  groupSizeMin: 1
  groupSizeMax: 3
  groupRadius: 4
  overrideLevelupChance: 65
- prefab: Surtling
  biome: PrimevalForest
  biomeArea: median
  spawnChance: 10
  maxSpawned: 2
  spawnInterval: 750
  maxLevel: 3
  minAltitude: -1
  maxAltitude: 1000
  requiredEnvironments: PrimeClear
  spawnDistance: 15
  groupSizeMin: 1
  groupSizeMax: 2
  groupRadius: 4
  overrideLevelupChance: 40