- prefab: MWL_StoneCastle1
  biome: Mountain
  quantity: 5
  minDistance: 0.05
  minAltitude: 80
  prioritized: true
  group: Mountain_Stone_Large
  minDistanceFromSimilar: 1024
  slopeRotation: true
  minTerrainDelta: 7
  maxTerrainDelta: 15
  exteriorRadius: 20
  randomDamage: true
- prefab: MWL_StoneFort1
  biome: Mountain
  quantity: 10
  minDistance: 0.05
  minAltitude: 70
  prioritized: true
  group: Mountain_Stone_Small
  minDistanceFromSimilar: 256
  exteriorRadius: 15
- prefab: MWL_StoneHall1
  biome: Mountain
  quantity: 10
  minDistance: 0.05
  minAltitude: 80
  prioritized: true
  group: Mountain_Stone_Medium
  minDistanceFromSimilar: 512
  exteriorRadius: 15
- prefab: MWL_StoneTavern1
  biome: Mountain
  quantity: 10
  minDistance: 0.05
  minAltitude: 75
  prioritized: true
  group: Mountain_Stone_Medium
  minDistanceFromSimilar: 512
  maxTerrainDelta: 18
  exteriorRadius: 15
  randomDamage: true
- prefab: MWL_StoneTower1
  biome: Mountain
  quantity: 10
  minDistance: 0.05
  minAltitude: 80
  prioritized: true
  group: Mountain_Stone_Small
  minDistanceFromSimilar: 256
  maxTerrainDelta: 2
  exteriorRadius: 8
  randomDamage: true
- prefab: MWL_StoneTower2
  biome: Mountain
  quantity: 10
  minDistance: 0.05
  minAltitude: 70
  prioritized: true
  group: Mountain_Stone_Small
  minDistanceFromSimilar: 256
  exteriorRadius: 10
- prefab: MWL_WoodBarn1
  biome: Mountain
  quantity: 10
  minDistance: 0.05
  minAltitude: 80
  prioritized: true
  group: Mountain_Wood_1
  minDistanceFromSimilar: 512
  maxTerrainDelta: 3
  exteriorRadius: 20
- prefab: MWL_WoodFarm1
  biome: Mountain
  quantity: 10
  minDistance: 0.05
  minAltitude: 70
  prioritized: true
  group: Mountain_Wood_1
  minDistanceFromSimilar: 512
  maxTerrainDelta: 7
  exteriorRadius: 18
- prefab: MWL_WoodHouse1
  biome: Mountain
  quantity: 5
  minDistance: 0.05
  minAltitude: 90
  prioritized: true
  group: Mountain_Wood_2
  minDistanceFromSimilar: 512
  exteriorRadius: 10
  randomDamage: true
