#################################################
# Shrine of Challenge Rewards Configuration
#################################################
# Rewards configurations have a number of key values
#  Coin:                                 |- The name of the reward, this will be the diplayed name if there is no localization for this reward, which is likely the case for any custom entries.
#    enabled: true                       |- Whether or not the reward is enabled, you can use this to disable any vanilla rewards you do not want. At least 1 reward must be available at ALL times.
#    resource_cost: 5                    |- This is the cost to gain 1 of the particular reward. Points are generated based on how many monsters are spawned.
#    resource_prefab: "Coins"            |- This is the unity prefab name for a resource, you will often see mods list the prefabs they have added. Prefabs are also listed on the valheim wiki.
#    required_boss: "None"               |- This must be one of the following values: "None" "Eikythr" "TheElder" "BoneMass" "Moder" "Yagluth" "TheQueen"
rewards:
  Coin:
    resource_cost: 5
    required_boss: None
    resource_prefab: Coins
    enabled: true
  Wood:
    resource_cost: 12
    required_boss: Eikythr
    resource_prefab: Wood
    enabled: true
  CoreWood:
    resource_cost: 20
    required_boss: BoneMass
    resource_prefab: RoundLog
    enabled: true
  FineWood:
    resource_cost: 26
    required_boss: Moder
    resource_prefab: FineWood
    enabled: true
  Copper:
    resource_cost: 45
    required_boss: TheElder
    resource_prefab: CopperOre
    enabled: true
  Tin:
    resource_cost: 40
    required_boss: TheElder
    resource_prefab: TinOre
    enabled: true
  Iron:
    resource_cost: 60
    required_boss: BoneMass
    resource_prefab: IronScrap
    enabled: true
  Silver:
    resource_cost: 70
    required_boss: Moder
    resource_prefab: SilverOre
    enabled: true
  Blackmetal:
    resource_cost: 80
    required_boss: Yagluth
    resource_prefab: BlackMetalScrap
    enabled: true
  Tar:
    resource_cost: 60
    required_boss: Yagluth
    resource_prefab: Tar
    enabled: true
  Guck:
    resource_cost: 40
    required_boss: BoneMass
    resource_prefab: Guck
    enabled: false
  Sap:
    resource_cost: 100
    required_boss: TheQueen
    resource_prefab: Sap
    enabled: true
  SoftTissue:
    resource_cost: 140
    required_boss: TheQueen
    resource_prefab: Softtissue
    enabled: true

