###################################################################################################################################################
# Wild Shrine Configuration
###################################################################################################################################################
# wildShrines:
# - definitionForWildShrine: VF_wild_shrine_green1                    |- The prefab that this set of configuration will be applied to
#   wildShrineNameLocalization: $wild_shrine_green                    |- The localization for the prefabs name (when hovered over) this uses a lookup value but defaults to its literal value
#   wildShrineRequestLocalization: $wild_shrine_green_request         |- What the shrine says when you interact with it
#   shrineUnacceptedTributeLocalization: $wild_shrine_not_interested  |- What the shrine says when you offer an incorrect tribute
#   shrineLargerTributeRequiredLocalization: $wild_shrine_hungry      |- What the shrine says when you do not offer enough tribute
#   wildShrineLevelsConfig:                                           |- Level configurations related to this shrine
#   - tributeName: TrophyBoar                                         |- The prefab name of the tribute required to activate this level
#     tributeAmount: 4                                                |- Amount of the tribute required to activate this level
#     rewards:                                                        |- Rewards for this level in the format of Prefab: cost eg: RawMeat: 14.
#       LeatherScraps: 14
#       RawMeat: 12
#     hardMode: false                                                 |- If hardmode should be enabled for this level (doubles the spawn point pool and gives 50% more rewards)
#     siegeMode: false                                                |- If siege mode should be enabled for this level (double the number of waves 4->8 and gives 50% more rewards)
#     wildshrineWaveStartLocalization: $wild_boars_attack             |- Localization text to display when this wave starts
#     wildshrineWaveEndLocalization: $wild_boars_defeated             |- Localization text to display when this wave is finished
#     wildLevelDefinition:
#       levelIndex: 2                                                 |- The difficulty level for this wave, valid values are 1+ (Refer to the readme for a breakdown of this equation)
#       biome: Meadows                                                |- The biome this wave is for, this impacts creature selection
#       waveFormat: Tutorial                                          |- The wavestyle this uses (from wavestyles.yml), this governs which catagories and the percentage makeup of the wave
#       levelWarningLocalization: $meadows_warning_wilderness         |- Localization for a between phase warning (often not used)
#       maxCreaturesPerPhaseOverride: 15                              |- Overrides the max creatures per wave to be this value (overrides the global config)
#       onlySelectMonsters:                                           |- Set of monsters that can be selected (From monsters.yml)
#       - Boar
#       - Greyling
#       excludeSelectMonsters:                                        |- Set of monsters that can't be selected (from monsters.yml) best used when OnlySelected is not set.
#       commonSpawnModifiers:                                         |- Spawn modifiers for common creatures
#         linearIncreaseRandomWaveAdjustment: true
#       rareSpawnModifiers:                                           |- Spawn modifiers for rare creatures
#       eliteSpawnModifiers:                                          |- Spawn modifiers for elite creatures

wildShrines:
- definitionForWildShrine: VF_wild_shrine_green1
  wildShrineNameLocalization: $wild_shrine_green
  wildShrineRequestLocalization: $wild_shrine_green_request
  shrineUnacceptedTributeLocalization: $wild_shrine_not_interested
  shrineLargerTributeRequiredLocalization: $wild_shrine_hungry
  wildShrineLevelsConfig:
  - tributeName: TrophyBoar
    tributeAmount: 3
    rewards:
      EssenceMagic: 10
      DustMagic: 10
      ReagentMagic: 15
    hardMode: false
    siegeMode: false
    wildshrineWaveStartLocalization: $wild_boars_attack
    wildshrineWaveEndLocalization: $wild_boars_defeated
    wildLevelDefinition:
      levelIndex: 2
      biome: Meadows
      waveFormat: Starter
      levelWarningLocalization: $meadows_warning_wilderness
      maxCreaturesPerPhaseOverride: 15
      onlySelectMonsters:
      - Boar
      - Greyling
      - Neck
      excludeSelectMonsters: 
      commonSpawnModifiers:
        linearIncreaseRandomWaveAdjustment: true
      rareSpawnModifiers: 
      eliteSpawnModifiers:
- definitionForWildShrine: VF_wild_shrine_blue1
  wildShrineNameLocalization: $wild_shrine_blackforest
  wildShrineRequestLocalization: $wild_shrine_blackforest_request
  shrineUnacceptedTributeLocalization: $wild_shrine_not_interested
  shrineLargerTributeRequiredLocalization: $wild_shrine_hungry
  wildShrineLevelsConfig:
  - tributeName: TrophyGreydwarf
    tributeAmount: 3
    rewards:
      DustRare: 5
      EssenceRare: 5
      ReagentRare: 10
    hardMode: false
    siegeMode: false
    wildshrineWaveStartLocalization: $wild_greydwarfs_attack
    wildshrineWaveEndLocalization: $wild_greydwarfs_defeated
    wildLevelDefinition:
      levelIndex: 3
      biome: BlackForest
      waveFormat: Easy
      levelWarningLocalization: $blackforest_warning_wilderness
      maxCreaturesPerPhaseOverride: 15
      onlySelectMonsters:
      - GreyDwarf
      - GreyDwarfBrute
      - GreyDwarfShaman
      excludeSelectMonsters: 
      commonSpawnModifiers:
        linearIncreaseRandomWaveAdjustment: true
      rareSpawnModifiers: 
      eliteSpawnModifiers: 
  - tributeName: TrophySkeleton
    tributeAmount: 3
    rewards:
      DustRare: 5
      EssenceRare: 5
      ReagentRare: 10
    hardMode: false
    siegeMode: false
    wildshrineWaveStartLocalization: $wild_skeleton_attack
    wildshrineWaveEndLocalization: $wild_skeleton_defeated
    wildLevelDefinition:
      levelIndex: 4
      biome: BlackForest
      waveFormat: easy
      levelWarningLocalization: $blackforest_warning_wilderness
      maxCreaturesPerPhaseOverride: 15
      onlySelectMonsters:
      - Skeleton
      - SkeletonArcher
      - RancidSkeleton
      excludeSelectMonsters: 
      commonSpawnModifiers:
        linearIncreaseRandomWaveAdjustment: true
      rareSpawnModifiers:
        linearIncreaseRandomWaveAdjustment: true
      eliteSpawnModifiers: 
- definitionForWildShrine: VF_wild_shrine_green2
  wildShrineNameLocalization: $wild_shrine_swamp
  wildShrineRequestLocalization: $wild_shrine_swamp_request
  shrineUnacceptedTributeLocalization: $wild_shrine_not_interested
  shrineLargerTributeRequiredLocalization: $wild_shrine_hungry
  wildShrineLevelsConfig:
  - tributeName: TrophyDraugr
    tributeAmount: 3
    rewards:
      DustRare: 5
      EssenceRare: 5
      ReagentRare: 10
      DustEpic: 15
      EssenceEpic: 15
      ReagentEpic: 20
    hardMode: false
    siegeMode: false
    wildshrineWaveStartLocalization: $wild_undead_attack
    wildshrineWaveEndLocalization: $wild_undead_defeated
    wildLevelDefinition:
      levelIndex: 7
      biome: Swamp
      waveFormat: Normal
      levelWarningLocalization: $swamp_warning_wilderness
      maxCreaturesPerPhaseOverride: 10
      onlySelectMonsters:
      - Draugr
      - DraugrArcher
      - Leech
      - Blob
      excludeSelectMonsters: 
      commonSpawnModifiers:
        linearIncreaseRandomWaveAdjustment: true
      rareSpawnModifiers:
        linearIncreaseRandomWaveAdjustment: true
      eliteSpawnModifiers:
        linearIncreaseRandomWaveAdjustment: true
- definitionForWildShrine: VF_wild_shrine_blue2
  wildShrineNameLocalization: $wild_shrine_mountain
  wildShrineRequestLocalization: $wild_shrine_mountain_request
  shrineUnacceptedTributeLocalization: $wild_shrine_not_interested
  shrineLargerTributeRequiredLocalization: $wild_shrine_hungry
  wildShrineLevelsConfig:
  - tributeName: TrophyWolf
    tributeAmount: 3
    rewards:
      DustEpic: 20
      EssenceEpic: 20
      ReagentEpic: 25
      DustLegendary: 25
      EssenceLegendary: 25
      ReagentLegendary: 35
    hardMode: false
    siegeMode: false
    wildshrineWaveStartLocalization: $wild_wolves_attack
    wildshrineWaveEndLocalization: $wild_wolves_defeated
    wildLevelDefinition:
      levelIndex: 12
      biome: Mountain
      waveFormat: Normal
      levelWarningLocalization: $mountain_warning_wilderness
      maxCreaturesPerPhaseOverride: 10
      onlySelectMonsters:
      - Wolf
      - Fenring
      - Ulv
      - Cultist
      excludeSelectMonsters: 
      commonSpawnModifiers:
        linearIncreaseRandomWaveAdjustment: true
      rareSpawnModifiers:
        linearIncreaseRandomWaveAdjustment: true
      eliteSpawnModifiers:
        linearIncreaseRandomWaveAdjustment: true
- definitionForWildShrine: VF_wild_shrine_yellow1
  wildShrineNameLocalization: $wild_shrine_plains
  wildShrineRequestLocalization: $wild_shrine_plains_request
  shrineUnacceptedTributeLocalization: $wild_shrine_not_interested
  shrineLargerTributeRequiredLocalization: $wild_shrine_hungry
  wildShrineLevelsConfig:
  - tributeName: TrophyGoblin
    tributeAmount: 3
    rewards:
      DustEpic: 15
      EssenceEpic: 15
      ReagentEpic: 20
      DustLegendary: 25
      EssenceLegendary: 25
      ReagentLegendary: 35
    hardMode: false
    siegeMode: false
    wildshrineWaveStartLocalization: $wild_fulings_attack
    wildshrineWaveEndLocalization: $wild_fulings_defeated
    wildLevelDefinition:
      levelIndex: 16
      biome: Plains
      waveFormat: Hard
      levelWarningLocalization: $plains_warning_wilderness
      maxCreaturesPerPhaseOverride: 10
      onlySelectMonsters:
      - Fuling
      - FulingArcher
      - FulingShaman
      - FulingBerserker
      excludeSelectMonsters: 
      commonSpawnModifiers:
        linearIncreaseRandomWaveAdjustment: true
      rareSpawnModifiers:
        linearIncreaseRandomWaveAdjustment: true
      eliteSpawnModifiers:
        linearIncreaseRandomWaveAdjustment: true
- definitionForWildShrine: VF_wild_shrine_purple1
  wildShrineNameLocalization: $wild_shrine_mistlands
  wildShrineRequestLocalization: $wild_shrine_mistlands_request
  shrineUnacceptedTributeLocalization: $wild_shrine_not_interested
  shrineLargerTributeRequiredLocalization: $wild_shrine_hungry
  wildShrineLevelsConfig:
  - tributeName: TrophySeeker
    tributeAmount: 3
    rewards:
      DustEpic: 15
      EssenceEpic: 15
      ReagentEpic: 20
      DustLegendary: 25
      EssenceLegendary: 25
      ReagentLegendary: 35
      DustMythic: 40
      EssenceMythic: 40
      ReagentMythic: 50
    hardMode: false
    siegeMode: false
    wildshrineWaveStartLocalization: $wild_seekers_attack
    wildshrineWaveEndLocalization: $wild_seekers_defeated
    wildLevelDefinition:
      levelIndex: 20
      biome: Mistlands
      waveFormat: Hard
      levelWarningLocalization: $mistlands_warning_wilderness
      maxCreaturesPerPhaseOverride: 10
      onlySelectMonsters:
      - Seeker
      - SeekerBrood
      - SeekerSoldier
      - Tick
      excludeSelectMonsters: 
      commonSpawnModifiers:
        linearIncreaseRandomWaveAdjustment: true
      rareSpawnModifiers:
        linearIncreaseRandomWaveAdjustment: true
      eliteSpawnModifiers:
        linearIncreaseRandomWaveAdjustment: true
