- prefab: MWL_RuinsArena2
  biome: BlackForest
  quantity: 5
  minDistance: 0.25
  maxDistance: 0.4
  minAltitude: 1
  prioritized: true
  group: Ruins_large
  minDistanceFromSimilar: 1024
  maxTerrainDelta: 2
  exteriorRadius: 20
- prefab: MWL_RuinsCastle1
  biome: BlackForest
  quantity: 15
  minDistance: 0.05
  maxDistance: 0.2
  minAltitude: 1
  prioritized: true
  group: Ruins_medium
  minDistanceFromSimilar: 512
  discoverLabel: Midgard Outpost
  maxTerrainDelta: 2
  exteriorRadius: 12.5
  randomDamage: true
- prefab: MWL_RuinsCastle3
  biome: BlackForest
  quantity: 5
  minDistance: 0.15
  maxDistance: 0.3
  minAltitude: 0
  maxAltitude: 2
  prioritized: true
  group: Ruins_large
  minDistanceFromSimilar: 512
  maxTerrainDelta: 2
  exteriorRadius: 20
  randomDamage: true
- prefab: MWL_RuinsTower3
  biome: BlackForest
  quantity: 15
  minDistance: 0.05
  maxDistance: 0.2
  minAltitude: 1
  prioritized: true
  group: Ruins_medium
  minDistanceFromSimilar: 512
  discoverLabel: Midgard Outpost
  maxTerrainDelta: 2
  exteriorRadius: 8
  randomDamage: true
- prefab: MWL_RuinsTower8
  biome: BlackForest
  quantity: 10
  minDistance: 0.05
  maxDistance: 0.2
  minAltitude: -2
  maxAltitude: 0.5
  prioritized: true
  group: Ruins_medium
  minDistanceFromSimilar: 512
  randomRotation: true
  maxTerrainDelta: 2
  exteriorRadius: 15
  randomDamage: true
- prefab: MWL_Tavern1
  biome: BlackForest
  quantity: 15
  minDistance: 0.15
  maxDistance: 0.3
  minAltitude: 1
  prioritized: true
  group: Wood_small
  minDistanceFromSimilar: 256
  discoverLabel: Skald's Respite
  maxTerrainDelta: 2
  exteriorRadius: 12
  randomDamage: true
- prefab: MWL_WoodTower1
  biome: BlackForest
  quantity: 10
  minDistance: 0.05
  maxDistance: 0.2
  minAltitude: 1
  prioritized: true
  group: Wood_small
  minDistanceFromSimilar: 256
  discoverLabel: Midgard Scout Tower
  maxTerrainDelta: 2
  exteriorRadius: 8
  randomDamage: true
- prefab: MWL_WoodTower2
  biome: BlackForest
  quantity: 10
  minDistance: 0.15
  maxDistance: 0.3
  minAltitude: 1
  prioritized: true
  group: Wood_small
  minDistanceFromSimilar: 256
  maxTerrainDelta: 2
  exteriorRadius: 7
  randomDamage: true
- prefab: MWL_WoodTower3
  biome: BlackForest
  quantity: 10
  minDistance: 0.15
  maxDistance: 0.3
  minAltitude: 1
  prioritized: true
  group: Wood_medium
  minDistanceFromSimilar: 512
  maxTerrainDelta: 2
  exteriorRadius: 24
  randomDamage: true
