- prefab: MineRock_gold
  enabled: true
  max: 2
  scaleMin: 295
  scaleMax: 296
  biome: BlackForest
  maxAltitude: 1000
  maxTerrainDelta: 2
  groundOffset: -0.3
- prefab: MineRock_iron
  enabled: true
  max: 2
  scaleMin: 295
  scaleMax: 296
  biome: Swamp
  maxAltitude: 1000
  maxTerrainDelta: 2
  groundOffset: -0.3
- prefab: MineRock_silver_small
  enabled: true
  max: 1
  scaleMin: 295
  scaleMax: 296
  biome: Mountain
  minAltitude: -1000
  maxAltitude: 100
  maxTerrainDelta: 2
  groundOffset: -1.3
- prefab: MineRock_blackmetal
  enabled: true
  max: 2
  scaleMin: 295
  scaleMax: 296
  biome: Plains
  maxAltitude: 1000
  maxTerrainDelta: 2
  groundOffset: -0.3
- prefab: MineRock_coal
  enabled: true
  max: 2
  scaleMin: 300
  scaleMax: 300
  biome: Swamp
  maxAltitude: 1000
  maxTerrainDelta: 2
  groundOffset: -0.3
