Deer: 1
Boar: 1
Neck: 1
Greyling: 1
Eikthyr: 5
Greydwarf: 2
Greydwarf_Shaman: 2
Greydwarf_Elite: 3
Ghost: 3
Skeleton: 1
Troll: 4
gd_king: 10
Leech: 2
Blob: 2
Draugr: 2
Draugr_Ranged: 2
Draugr_Elite: 4
BlobElite: 4
Wraith: 4
Abomination: 5
Bonemass: 15
Wolf: 2
Fenring: 4
Fenring_Cultist: 5
Ulv: 4
Hatchling: 3
StoneGolem: 7
Fenring_Cultist_Hildir: 20
Skeleton_Hildir: 20
GoblinShaman_Hildir: 30
GoblinBrute_Hildir: 30
Dragon: 30
Goblin: 5
BlobTar: 10
Lox: 6
Serpent: 10
GoblinKing: 50
Seeker: 10
SeekerBrute: 15
SeekerBrood: 6
Hare: 6
Tick: 6
Gjall: 20
Dverger: 20
DvergerArbalest: 20
DvergerMage: 20
DvergerMageFire: 20
DvergerMageIce: 20
DvergerMageSupport: 20
SeekerQueen: 100
Surtling: 3
Dino1_coe: 2
Dino5_coe: 3
Dino17_coe: 2
Dino18_coe: 5

