- prefab: MWL_GuckPit1
  biome: Swamp
  biomeArea: median
  quantity: 20
  minDistance: 0.05
  minAltitude: 0
  prioritized: true
  group: Swamp_small
  minDistanceFromSimilar: 256
  maxTerrainDelta: 5
  exteriorRadius: 8
- prefab: MWL_SwampAltar1
  biome: Swamp
  biomeArea: median
  quantity: 15
  minDistance: 0.05
  minAltitude: -1
  prioritized: true
  group: Swamp_altar
  minDistanceFromSimilar: 512
  maxTerrainDelta: 8
  exteriorRadius: 8
  clearArea: true
  noBuild: true
- prefab: MWL_SwampAltar2
  biome: Swamp
  biomeArea: median
  quantity: 10
  minDistance: 0.05
  minAltitude: -1
  prioritized: true
  group: Swamp_altar
  minDistanceFromSimilar: 512
  maxTerrainDelta: 8
  exteriorRadius: 15
- prefab: MWL_SwampAltar3
  biome: Swamp
  biomeArea: median
  quantity: 10
  minDistance: 0.05
  minAltitude: -1
  prioritized: true
  group: Swamp_altar
  minDistanceFromSimilar: 512
  maxTerrainDelta: 8
  exteriorRadius: 15
  clearArea: true
  noBuild: true
- prefab: MWL_SwampAltar4
  biome: Swamp
  biomeArea: median
  quantity: 10
  minDistance: 0.05
  minAltitude: -1
  prioritized: true
  group: Swamp_altar
  minDistanceFromSimilar: 512
  maxTerrainDelta: 8
  exteriorRadius: 10
- prefab: MWL_SwampCastle2
  biome: Swamp
  biomeArea: median
  quantity: 10
  minDistance: 0.05
  minAltitude: 0
  prioritized: true
  group: Swamp_medium
  minDistanceFromSimilar: 512
  maxTerrainDelta: 8
  exteriorRadius: 15
- prefab: MWL_SwampGrave1
  biome: Swamp
  biomeArea: median
  quantity: 25
  minDistance: 0.05
  minAltitude: 0
  prioritized: true
  group: Swamp_medium
  minDistanceFromSimilar: 512
  maxTerrainDelta: 8
  exteriorRadius: 10
  clearArea: true
  noBuild: true
- prefab: MWL_SwampHouse1
  biome: Swamp
  biomeArea: median
  quantity: 20
  minDistance: 0.05
  prioritized: true
  group: Swamp_small
  minDistanceFromSimilar: 256
  maxTerrainDelta: 8
  exteriorRadius: 5
  clearArea: true
  noBuild: true
- prefab: MWL_SwampRuin1
  biome: Swamp
  biomeArea: median
  quantity: 25
  minDistance: 0.05
  minAltitude: -1
  prioritized: true
  group: Swamp_medium
  minDistanceFromSimilar: 512
  maxTerrainDelta: 8
  exteriorRadius: 10
- prefab: MWL_SwampTower1
  biome: Swamp
  biomeArea: median
  quantity: 20
  minDistance: 0.05
  minAltitude: 0
  prioritized: true
  group: Swamp_small
  minDistanceFromSimilar: 256
  maxTerrainDelta: 8
  exteriorRadius: 8
- prefab: MWL_SwampTower2
  biome: Swamp
  biomeArea: median
  quantity: 25
  minDistance: 0.05
  minAltitude: 0
  prioritized: true
  group: Swamp_tower
  minDistanceFromSimilar: 1024
  maxTerrainDelta: 8
  exteriorRadius: 8
  noBuild: true
- prefab: MWL_SwampTower3
  biome: Swamp
  biomeArea: median
  quantity: 25
  minDistance: 0.05
  minAltitude: 0
  prioritized: true
  group: Swamp_large
  minDistanceFromSimilar: 1024
  maxTerrainDelta: 8
  exteriorRadius: 15
- prefab: MWL_SwampWell1
  biome: Swamp
  quantity: 20
  minDistance: 0.05
  minAltitude: 0
  prioritized: true
  group: Swamp_small
  minDistanceFromSimilar: 256
  maxTerrainDelta: 8
  exteriorRadius: 15
  clearArea: true
  noBuild: true
