- prefab: lox_ribs
  min: 0
  max: 0.25
  scaleMin: 1.5,1.5,2.25
  scaleMax: 2,2,3.25
  scaleUniform: false
  randTilt: 25
  biome: RockyCoast
  minAltitude: -2
  maxAltitude: 20
  minTilt: 0
  maxTilt: 35
  terrainDeltaRadius: 0
  minTerrainDelta: 0
  maxTerrainDelta: 10
  groundOffset: -1
  groupSizeMin: 1
  groupSizeMax: 1
  groupRadius: 4
  clearRadius: 5
  clearArea: true
- prefab: highstone
  min: 1
  max: 2
  scaleMin: 0.75
  scaleMax: 1
  randTilt: 75
  biome: RockyCoast
  minAltitude: -2
  maxAltitude: 20
  minTilt: 5
  maxTilt: 90
  terrainDeltaRadius: 0
  minTerrainDelta: 0
  maxTerrainDelta: 10
  groundOffset: -1
  groupSizeMin: 1
  groupSizeMax: 1
- prefab: widestone
  min: 2
  max: 3
  scaleMin: 0.5
  scaleMax: 1
  randTilt: 75
  biome: RockyCoast
  minAltitude: -2
  maxAltitude: 20
  minTilt: 0
  maxTilt: 90
  terrainDeltaRadius: 0
  minTerrainDelta: 0
  maxTerrainDelta: 10
  groundOffset: -0.25
  groupSizeMin: 1
  groupSizeMax: 1
- prefab: TarLiquid
  min: 0
  max: 0.25
  biome: RockyCoast
  minAltitude: 2
  maxAltitude: 15
  groundOffset: -20
- prefab: RockFingerBroken
  min: 0
  max: 0.2
  scaleMin: 1,1,0.65
  scaleMax: 1.2,1.2,0.85
  scaleUniform: false
  randTilt: 25
  biome: RockyCoast
  minAltitude: -2
  maxAltitude: 20
  minTilt: 0
  maxTilt: 65
  terrainDeltaRadius: 0
  minTerrainDelta: 0
  maxTerrainDelta: 10
  groundOffset: -3.5
  groupSizeMin: 0
  groupSizeMax: 1
- prefab: rock3_mountain
  min: 0
  max: 1
  scaleMin: 0.4
  scaleMax: 0.6
  randTilt: 55
  biome: RockyCoast
  minAltitude: -2
  maxAltitude: 20
  minTilt: 0
  maxTilt: 90
  terrainDeltaRadius: 0
  minTerrainDelta: 0
  maxTerrainDelta: 10
  groundOffset: -4
  groupSizeMin: 1
  groupSizeMax: 1
- prefab: rock2_mountain
  min: 0
  max: 1
  scaleMin: 0.35
  scaleMax: 0.55
  randTilt: 55
  biome: RockyCoast
  minAltitude: -2
  maxAltitude: 20
  minTilt: 0
  maxTilt: 90
  terrainDeltaRadius: 0
  minTerrainDelta: 0
  maxTerrainDelta: 10
  groundOffset: -2
  groupSizeMin: 1
  groupSizeMax: 1
- prefab: rock1_mountain
  min: 0
  max: 1
  scaleMin: 0.35
  scaleMax: 0.55
  randTilt: 55
  biome: RockyCoast
  minAltitude: -2
  maxAltitude: 20
  minTilt: 0
  maxTilt: 90
  terrainDeltaRadius: 0
  minTerrainDelta: 0
  maxTerrainDelta: 10
  groundOffset: -2
  groupSizeMin: 1
  groupSizeMax: 1
- prefab: Rock_3
  min: 4
  max: 8
  scaleMin: 2.5,2.5,1
  scaleMax: 4,4,1.25
  scaleUniform: false
  randTilt: 35
  biome: RockyCoast
  minAltitude: -2
  maxAltitude: 25
  minTilt: 0
  maxTilt: 35
  groundOffset: -0.5
  groupSizeMin: 1
  groupSizeMax: 2
- prefab: Rock_7
  min: 4
  max: 8
  scaleMin: 2.25,2,1
  scaleMax: 3.25,3.25,1.5
  scaleUniform: false
  randTilt: 35
  biome: RockyCoast
  minAltitude: -2
  maxAltitude: 25
  minTilt: 0
  maxTilt: 35
  groundOffset: -0.5
  groupSizeMin: 1
  groupSizeMax: 2
- prefab: StatueSeed
  min: 2
  max: 3
  scaleMin: 1.25
  scaleMax: 1.75
  randTilt: 45
  biome: RockyCoast
  minAltitude: -2
  maxAltitude: 25
  minTilt: 0
  maxTilt: 45
  groundOffset: -1
  groupSizeMin: 1
  groupSizeMax: 1
- prefab: RockDolmen_1
  min: 5
  max: 10
  scaleMin: 0.85
  scaleMax: 1.25
  randTilt: 120
  biome: RockyCoast
  minAltitude: 0
  maxAltitude: 20
  minTilt: 0
  maxTilt: 75
  groundOffset: -0.1
  groupSizeMin: 1
  groupSizeMax: 1
- prefab: RockDolmen_2
  min: 5
  max: 10
  scaleMin: 0.85
  scaleMax: 1.25
  randTilt: 120
  biome: RockyCoast
  minAltitude: 0
  maxAltitude: 20
  minTilt: 0
  maxTilt: 75
  groundOffset: -0.1
  groupSizeMin: 1
  groupSizeMax: 1
- prefab: RockDolmen_3
  min: 5
  max: 10
  scaleMin: 0.85
  scaleMax: 1.25
  randTilt: 120
  biome: RockyCoast
  minAltitude: 0
  maxAltitude: 20
  minTilt: 0
  maxTilt: 75
  groundOffset: -0.1
  groupSizeMin: 1
  groupSizeMax: 1
- prefab: rock2_heath
  min: 2
  max: 4
  scaleMin: 0.75
  scaleMax: 1
  randTilt: 35
  chanceToUseGroundTilt: 0.25
  biome: RockyCoast
  minAltitude: -2
  maxAltitude: 15
  minTilt: 0
  maxTilt: 45
  terrainDeltaRadius: 0
  minTerrainDelta: 0
  maxTerrainDelta: 10
  groundOffset: -1
  groupSizeMin: 1
  groupSizeMax: 1
- prefab: rock4_heath
  min: 2
  max: 4
  scaleMin: 0.75
  scaleMax: 1
  randTilt: 35
  chanceToUseGroundTilt: 0.25
  biome: RockyCoast
  minAltitude: -1
  maxAltitude: 15
  minTilt: 0
  maxTilt: 45
  terrainDeltaRadius: 0
  minTerrainDelta: 0
  maxTerrainDelta: 10
  groundOffset: -2
  groupSizeMin: 1
  groupSizeMax: 1
- prefab: vfx_swamp_mist
  min: 0
  max: 0
  scaleMin: 5
  scaleMax: 6
  biome: RockyCoast
  minAltitude: 1
  maxAltitude: 15
  maxTerrainDelta: 2
  snapToWater: true
- prefab: rock2_heath
  min: 4
  max: 6
  scaleMin: 0.25
  scaleMax: 0.75
  randTilt: 55
  chanceToUseGroundTilt: 0.25
  biome: RockyCoast
  minAltitude: -2
  maxAltitude: 1
  minTilt: 0
  maxTilt: 65
  terrainDeltaRadius: 0
  minTerrainDelta: 0
  maxTerrainDelta: 10
  groundOffset: -1
  groupSizeMin: 1
  groupSizeMax: 1
- prefab: rock4_heath
  min: 4
  max: 6
  scaleMin: 0.25
  scaleMax: 0.75
  randTilt: 55
  chanceToUseGroundTilt: 0.25
  biome: RockyCoast
  minAltitude: -2
  maxAltitude: 1
  minTilt: 0
  maxTilt: 65
  terrainDeltaRadius: 0
  minTerrainDelta: 0
  maxTerrainDelta: 10
  groundOffset: -1
  groupSizeMin: 1
  groupSizeMax: 1
- prefab: rock2_mountain
  min: 4
  max: 6
  scaleMin: 0.45
  scaleMax: 0.75
  randTilt: 55
  chanceToUseGroundTilt: 0.25
  biome: RockyCoast
  minAltitude: -2
  maxAltitude: 1
  minTilt: 0
  maxTilt: 65
  terrainDeltaRadius: 0
  minTerrainDelta: 0
  maxTerrainDelta: 10
  groundOffset: -3
  groupSizeMin: 1
  groupSizeMax: 1
- prefab: rock1_mountain
  min: 4
  max: 6
  scaleMin: 0.45
  scaleMax: 0.75
  randTilt: 55
  chanceToUseGroundTilt: 0.25
  biome: RockyCoast
  minAltitude: -3
  maxAltitude: 1
  minTilt: 0
  maxTilt: 65
  terrainDeltaRadius: 0
  minTerrainDelta: 0
  maxTerrainDelta: 10
  groundOffset: -1
  groupSizeMin: 1
  groupSizeMax: 1
- prefab: FirTree_oldLog
  min: 8
  max: 12
  scaleMin: 1.25
  scaleMax: 1.5
  randTilt: 25
  chanceToUseGroundTilt: 0.25
  biome: RockyCoast
  minAltitude: -1.5
  maxAltitude: 0.5
  minTilt: 0
  maxTilt: 35
  terrainDeltaRadius: 0
  minTerrainDelta: 0
  maxTerrainDelta: 10
  groundOffset: -1
  groupSizeMin: 1
  groupSizeMax: 1
- prefab: stubbe
  min: 0
  max: 1
  scaleMin: 1.25
  scaleMax: 1.5
  randTilt: 25
  chanceToUseGroundTilt: 0.25
  biome: RockyCoast
  minAltitude: -1.5
  maxAltitude: 0.5
  minTilt: 0
  maxTilt: 35
  terrainDeltaRadius: 0
  minTerrainDelta: 0
  maxTerrainDelta: 10
  groundOffset: -1
  groupSizeMin: 1
  groupSizeMax: 1
- prefab: Flies
  min: 20
  max: 25
  scaleMin: 1.5
  scaleMax: 2.5
  biome: RockyCoast
  minAltitude: 0
  maxAltitude: 25
  maxTilt: 25
  maxTerrainDelta: 2
- prefab: shrub_2_heath
  min: 5
  max: 10
  scaleMin: .5
  scaleMax: .75
  biome: RockyCoast
  minAltitude: 1
  maxAltitude: 35
  maxTerrainDelta: 2
  groupSizeMin: 1
  groupSizeMax: 1
- prefab: SwampTree1
  min: 2
  max: 4
  scaleMin: 0.55,0.55,0.5
  scaleMax: 0.6,0.6,0.85
  scaleUniform: false
  randTilt: 50
  chanceToUseGroundTilt: 0.25
  biome: RockyCoast
  minAltitude: 1
  maxAltitude: 20
  minTilt: 5
  maxTilt: 40
  groundOffset: -0.25
  groupSizeMin: 1
  groupSizeMax: 1
- prefab: wood_wall_log
  min: 2
  max: 3
  scaleMin: 1.25
  scaleMax: 2
  randTilt: 160
  chanceToUseGroundTilt: 0.25
  biome: RockyCoast
  minAltitude: -2
  maxAltitude: 25
  minTilt: 0
  maxTilt: 80
- prefab: wood_wall_log_4x0.5
  min: 1
  max: 2
  scaleMin: 1.25
  scaleMax: 2
  randTilt: 120
  chanceToUseGroundTilt: 0.25
  biome: RockyCoast
  minAltitude: -2
  maxAltitude: 25
  minTilt: 0
  maxTilt: 55
- prefab: stone_wall_4x2
  min: 1
  max: 2
  scaleMin: 1
  scaleMax: 1
  randTilt: 15
  chanceToUseGroundTilt: 0.25
  biome: RockyCoast
  minAltitude: 3
  maxAltitude: 25
  minTilt: 0
  maxTilt: 15
  groundOffset: -0.25
  groupSizeMin: 1
  groupSizeMax: 3
  groupRadius: 12
- prefab: rock2_heath
  min: 6
  max: 8
  scaleMin: 1.5,1.5,1.25
  scaleMax: 2,2,1.5
  scaleUniform: false
  randTilt: 35
  chanceToUseGroundTilt: 0.25
  biome: RockyCoast
  biomeArea: edge
  minAltitude: 1
  maxAltitude: 30
  minTilt: 0
  maxTilt: 45
  terrainDeltaRadius: 0
  minTerrainDelta: 0
  maxTerrainDelta: 10
  groundOffset: -1
  groupSizeMin: 1
  groupSizeMax: 2
- prefab: rock4_heath
  min: 6
  max: 8
  scaleMin: 1
  scaleMax: 1.25
  randTilt: 35
  chanceToUseGroundTilt: 0.25
  biome: RockyCoast
  biomeArea: edge
  minAltitude: 1
  maxAltitude: 30
  minTilt: 0
  maxTilt: 45
  terrainDeltaRadius: 0
  minTerrainDelta: 0
  maxTerrainDelta: 10
  groundOffset: -1
  groupSizeMin: 1
  groupSizeMax: 2
- prefab: piece_sharpstakes
  min: 2
  max: 3
  scaleMin: 1
  scaleMax: 1.25
  randTilt: 45
  chanceToUseGroundTilt: 0.25
  biome: RockyCoast
  minAltitude: -2
  maxAltitude: 25
  minTilt: 0
  maxTilt: 45
  groundOffset: -0.35
- prefab: stake_wall
  min: 1
  max: 2
  scaleMin: 1
  scaleMax: 1.25
  randTilt: 65
  chanceToUseGroundTilt: 0.25
  biome: RockyCoast
  minAltitude: -2
  maxAltitude: 25
  minTilt: 5
  maxTilt: 65
  groundOffset: -0.65
  groupSizeMin: 1
  groupSizeMax: 3
  groupRadius: 12
- prefab: darkwood_raven
  min: 0
  max: 1
  randTilt: 30
  biome: RockyCoast
  minAltitude: -2
  maxAltitude: 25
  minTilt: 0
  maxTilt: 30
  groundOffset: -0.2
- prefab: darkwood_wolf
  min: 0
  max: 1
  randTilt: 30
  biome: RockyCoast
  minAltitude: -2
  maxAltitude: 25
  minTilt: 0
  maxTilt: 30
  groundOffset: -0.2
- prefab: darkwood_dragon
  min: 0
  max: 1
  randTilt: 30
  biome: RockyCoast
  minAltitude: -2
  maxAltitude: 25
  minTilt: 0
  maxTilt: 30
  groundOffset: -0.2
- prefab: shipwreck_karve_bottomboards
  min: 0
  max: 1
  randTilt: 30
  biome: RockyCoast
  minAltitude: -2
  maxAltitude: 3
  minTilt: 0
  maxTilt: 30
  groundOffset: -0.5
- prefab: shipwreck_karve_bow
  min: 1
  max: 1
  randTilt: 30
  biome: RockyCoast
  minAltitude: -2
  maxAltitude: 3
  minTilt: 0
  maxTilt: 30
  groundOffset: -0.75
- prefab: shipwreck_karve_stern
  min: 1
  max: 1
  randTilt: 30
  biome: RockyCoast
  minAltitude: -2
  maxAltitude: 3
  minTilt: 0
  maxTilt: 30
  groundOffset: -0.5
- prefab: shipwreck_karve_sternpost
  min: 1
  max: 2
  randTilt: 10
  biome: RockyCoast
  minAltitude: -2
  maxAltitude: 3
  minTilt: 0
  maxTilt: 15
  groundOffset: -3.5
- prefab: mountainkit_table
  min: 0
  max: 1
  randTilt: 60
  biome: RockyCoast
  minAltitude: -2
  maxAltitude: 25
  minTilt: 0
  maxTilt: 50
  groundOffset: -0.25
- prefab: mountainkit_chair
  min: 1
  max: 2
  randTilt: 25
  biome: RockyCoast
  minAltitude: -2
  maxAltitude: 25
  minTilt: 0
  maxTilt: 30
  groundOffset: -0.075
- prefab: goblin_pole
  min: 2
  max: 3
  scaleMin: 0.5
  scaleMax: 0.85
  randTilt: 120
  chanceToUseGroundTilt: 0.25
  biome: RockyCoast
  minAltitude: -2
  maxAltitude: 55
  minTilt: 0
  maxTilt: 75
  groundOffset: -0.25
- prefab: CastleKit_groundtorch_unlit
  min: 2
  max: 3
  scaleMin: 1.25
  scaleMax: 1.5
  randTilt: 55
  chanceToUseGroundTilt: 0.25
  biome: RockyCoast
  minAltitude: -2
  maxAltitude: 15
  minTilt: 0
  maxTilt: 45
- prefab: Pickable_Flint
  min: 5
  max: 15
  biome: RockyCoast
  minAltitude: -2
  maxAltitude: 1
  maxTerrainDelta: 2
- prefab: Pickable_Branch
  min: 5
  max: 7.5
  chanceToUseGroundTilt: 1
  biome: RockyCoast
  maxAltitude: 55
  maxTerrainDelta: 2
- prefab: Pickable_Stone
  min: 15
  max: 25
  chanceToUseGroundTilt: 1
  biome: RockyCoast
  minAltitude: -3
  maxAltitude: 55
  maxTerrainDelta: 2
  groupRadius: 1
- prefab: Pickable_Tar
  min: 0
  max: 1
  chanceToUseGroundTilt: 1
  biome: RockyCoast
  minAltitude: 0.25
  maxAltitude: 25
  groundOffset: 0.15
  groupRadius: 20
- prefab: Pickable_TarBig
  min: 0
  max: 0.25
  chanceToUseGroundTilt: 1
  biome: RockyCoast
  minAltitude: 0.25
  maxAltitude: 25
  groundOffset: 0.15
  groupRadius: 20
- prefab: MineRock_Tin
  min: 2
  max: 4
  chanceToUseGroundTilt: 1
  scaleMax: 1.25
  biome: RockyCoast
  minAltitude: -1
  maxAltitude: 1
  groundOffset: -0.5
  groupSizeMin: 1
  groupSizeMax: 2
- prefab: goblin_trashpile
  min: 2
  max: 3
  biome: RockyCoast
  minAltitude: -0.5
  maxAltitude: 1.5
  maxTerrainDelta: 2
  groundOffset: -0.1
- prefab: goblin_strawpile
  min: 10
  max: 15
  chanceToUseGroundTilt: 1
  biome: RockyCoast
  blockCheck: true
  minAltitude: -0.25
  maxAltitude: 0.75
  maxTerrainDelta: 0
  groupRadius: 5
  groundOffset: -0.1
- prefab: goblin_woodwall_2m
  min: 2
  max: 3
  scaleMin: 1.25
  randTilt: 120
  biome: RockyCoast
  minAltitude: -0.25
  maxAltitude: 2
  minTilt: 5
  maxTilt: 65
  maxTerrainDelta: 0
  groundOffset: -0.25
- prefab: shipwreck_karve_chest
  min: 1
  max: 1
  randTilt: 25
  biome: RockyCoast
  minAltitude: -0.5
  maxAltitude: 3
  minTilt: 0
  maxTilt: 35
  groundOffset: -0.4
- prefab: barrell
  min: 2
  max: 3
  randTilt: 65
  biome: RockyCoast
  minAltitude: -3
  maxAltitude: 0
- prefab: CastleKit_braided_box01
  min: 2
  max: 4
  randTilt: 65
  biome: RockyCoast
  minAltitude: -2
  maxAltitude: 1
- prefab: rock3_mountain
  min: 0
  max: 0.85
  scaleMin: 1.5,1.5,1.25
  scaleMax: 2,2,2.5
  scaleUniform: false
  randTilt: 160
  chanceToUseGroundTilt: 0.25
  biome: RockyCoast
  blockCheck: false
  minAltitude: -30
  maxAltitude: -5
  minTilt: 5
  maxTilt: 90
  terrainDeltaRadius: 0
  minTerrainDelta: 0
  maxTerrainDelta: 15
- prefab: rock2_mountain
  min: 0
  max: 0.85
  scaleMin: 1.5,1.5,2
  scaleMax: 2,2,4
  scaleUniform: false
  randTilt: 40
  chanceToUseGroundTilt: 0.25
  biome: RockyCoast
  blockCheck: false
  minAltitude: -30
  maxAltitude: -5
  minTilt: 5
  maxTilt: 85
  terrainDeltaRadius: 5
  minTerrainDelta: 1
  maxTerrainDelta: 15
- prefab: rock1_mountain
  min: 0
  max: 0.85
  scaleMin: 1.25,1.25,2
  scaleMax: 1.75,1.75,3
  scaleUniform: false
  randTilt: 55
  chanceToUseGroundTilt: 0.25
  biome: RockyCoast
  blockCheck: false
  minAltitude: -30
  maxAltitude: -5
  minTilt: 5
  maxTilt: 75
  terrainDeltaRadius: 8
  minTerrainDelta: 2
  maxTerrainDelta: 15
- prefab: RockFingerBroken
  min: 0
  max: 0.55
  scaleMin: 1.75,1.5,1.25
  scaleMax: 2.75,2.5,2
  scaleUniform: false
  randTilt: 25
  chanceToUseGroundTilt: 0.25
  biome: RockyCoast
  blockCheck: false
  minAltitude: -30
  maxAltitude: -5
  minTilt: 5
  maxTilt: 35
  terrainDeltaRadius: 5
  minTerrainDelta: 1
  maxTerrainDelta: 15
- prefab: rock3_mountain
  min: 3
  max: 6
  scaleMin: 0.5,0.5,0.75
  scaleMax: 0.75,0.75,1.5
  scaleUniform: false
  randTilt: 85
  chanceToUseGroundTilt: 0.25
  biome: RockyCoast
  blockCheck: false
  minAltitude: -30
  maxAltitude: -5
  minTilt: 15
  maxTilt: 100
  terrainDeltaRadius: 5
  minTerrainDelta: 1
  maxTerrainDelta: 15
- prefab: highstone
  min: 4
  max: 8
  scaleMin: 1.75,1.75,2
  scaleMax: 3,3,3
  scaleUniform: false
  randTilt: 45
  chanceToUseGroundTilt: 0.25
  biome: RockyCoast
  blockCheck: false
  minAltitude: -30
  maxAltitude: -5
  minTilt: 15
  maxTilt: 75
  terrainDeltaRadius: 6
  minTerrainDelta: 0
  maxTerrainDelta: 15
- prefab: mudpile2
  min: 1
  max: 3
  scaleMin: 0.5,0.5,0.2
  scaleMax: 0.7,0.7,0.3
  scaleUniform: false
  randTilt: 5
  chanceToUseGroundTilt: 1
  biome: RockyCoast
  blockCheck: false
  minAltitude: 6
  maxAltitude: 9
  maxTilt: 120
  terrainDeltaRadius: 1
  minTerrainDelta: 0
  maxTerrainDelta: 99
  snapToStaticSolid: true
  groundOffset: -1
  groupSizeMin: 1
  groupSizeMax: 3
  groupRadius: 1
- prefab: mudpile2
  min: 5
  max: 9
  scaleMin: 0.5,0.5,0.2
  scaleMax: 0.7,0.7,0.3
  scaleUniform: false
  randTilt: 5
  chanceToUseGroundTilt: 1
  biome: RockyCoast
  biomeArea: median
  blockCheck: false
  minAltitude: 9
  maxAltitude: 18
  maxTilt: 120
  terrainDeltaRadius: 1
  minTerrainDelta: 0
  maxTerrainDelta: 99
  snapToStaticSolid: true
  groundOffset: -1
  groupSizeMin: 3
  groupSizeMax: 5
  groupRadius: 1
- prefab: mudpile2
  min: 20
  max: 30
  scaleMin: 0.5,0.5,0.2
  scaleMax: 0.7,0.7,0.3
  scaleUniform: false
  randTilt: 5
  chanceToUseGroundTilt: 1
  biome: RockyCoast
  blockCheck: false
  minAltitude: 18
  maxAltitude: 1000
  maxTilt: 120
  terrainDeltaRadius: 1
  minTerrainDelta: 0
  maxTerrainDelta: 99
  snapToStaticSolid: true
  groundOffset: -1
  groupSizeMin: 5
  groupSizeMax: 8
  groupRadius: 1
- prefab: Spawner_BlobTar
  min: 3
  max: 7
  chanceToUseGroundTilt: 0
  biome: RockyCoast
  biomeArea: median
  blockCheck: false
  minAltitude: 4
  maxAltitude: 1000
  snapToStaticSolid: true
  groundOffset: 0
  groupSizeMin: 1
  groupSizeMax: 2
  groupRadius: 5
- prefab: Spawner_BlobTar
  min: 1
  max: 2
  chanceToUseGroundTilt: 0
  biome: RockyCoast
  blockCheck: false
  minAltitude: 4
  maxAltitude: 1000
  snapToStaticSolid: true
  groundOffset: 0
  groupSizeMin: 1
  groupSizeMax: 1
  groupRadius: 5