# Below you can find example groups. Groups are used to exclude or includeOverride quickly. They are reusable lists! 
# Please note that some of these groups/container limitations are kinda pointless but are here for example.
# Make sure to follow the format of the example below. If you have any questions, please ask in my discord.

# Full vanilla prefab name list: https://valheim-modding.github.io/Jotunn/data/prefabs/prefab-list.html
# Item prefab name list: https://valheim-modding.github.io/Jotunn/data/objects/item-list.html

# There are several predefined groups set up for you that are not listed. You can use these just like you would any group you create yourself.
# These are the "All", "Food", "Potion", "Fish", "Swords", "Bows", "Crossbows", "Axes", "Clubs", "Knives", "Pickaxes", "Polearms", "Spears", "Equipment", "Boss Trophy", "Trophy", "Crops", "Seeds", "Ores", "Metals", and "Woods" groups.
# The criteria for these groups are as follows:
# groups:
#   Food:
#     - Criteria: Both of the following properties must have a value greater than 0.0 on the sharedData property of the ItemDrop script:
#         - food
#         - foodStamina
#   Potion:
#     - Criteria: The following properties must meet the specified conditions on the sharedData property of the ItemDrop script:
#         - food > 0.0
#         - foodStamina == 0.0
#   Fish:
#     - itemType: Fish
#   Swords, Bows, Crossbows, Axes, Clubs, Knives, Pickaxes, Polearms, Spears:
#     - itemType: OneHandedWeapon, TwoHandedWeapon, TwoHandedWeaponLeft, Bow
#     - Criteria: Items in these groups have a specific skillType on the sharedData property of the ItemDrop script. Each group corresponds to the skillType as follows:
#         - Swords: skillType == Skills.SkillType.Swords
#         - Bows: skillType == Skills.SkillType.Bows
#         - Crossbows: skillType == Skills.SkillType.Crossbows
#         - Axes: skillType == Skills.SkillType.Axes
#         - Clubs: skillType == Skills.SkillType.Clubs
#         - Knives: skillType == Skills.SkillType.Knives
#         - Pickaxes: skillType == Skills.SkillType.Pickaxes
#         - Polearms: skillType == Skills.SkillType.Polearms
#         - Spears: skillType == Skills.SkillType.Spears
#            Example:   An item with itemType set to OneHandedWeapon and skillType set to Skills.SkillType.Swords would belong to the Swords group.
#   Armor:
#     - itemType: Chest, Legs, Hands, Helmet, Shoulder
#   Equipment:
#     - itemType: Torch
#   Boss Trophy:
#     - itemType: Trophie
#     - Criteria: sharedData.m_name ends with any of the following boss names:
#         - eikthyr, elder, bonemass, dragonqueen, goblinking, SeekerQueen
#   Trophy:
#     - itemType: Trophie
#     - Criteria: sharedData.m_name does not end with any boss names
#   Crops:
#     - itemType: Material
#     - Criteria: Can be cultivated and grown into a pickable object with an amount greater than 1
#   Seeds:
#     - itemType: Material
#     - Criteria: Can be cultivated and grown into a pickable object with an amount equal to 1
#   Ores:
#     - itemType: Material
#     - Criteria: Can be processed by any of the following smelters:
#         - smelter
#         - blastfurnace
#   Metals:
#     - itemType: Material
#     - Criteria: Is the result of processing an ore in any of the following smelters:
#         - smelter
#         - blastfurnace
#   Woods:
#     - itemType: Material
#     - Criteria: Can be processed by the charcoal_kiln smelter
#   All:
#     - Criteria: Item has an ItemDrop script and all needed fields are populated. (all items)


groups:
  Arrows:
    - ArrowBronze
    - ArrowCarapace
    - ArrowFire
    - ArrowFlint
    - ArrowFrost
    - ArrowIron
    - ArrowNeedle
    - ArrowObsidian
    - ArrowPoison
    - ArrowSilver
    - ArrowWood
    - draugr_arrow
  Scraps:
    - BlackMetalScrap
    - BronzeScrap
    - CopperScrap
    - IronScrap
    - LeatherScraps
  Tier2Items:
    - Bronze
    - PickaxeBronze
    - ArmorBronzeChest
    - ArmorBrozeLeggings

# Please note that the inventory and hotbar sections are exclusive.
# If the item is excluded from the inventory but the item is in the hotbar, it will be dropped in the hotbar. This is the same for the other way around.
# To explain more simply, if you want to keep an item no matter what, you must include it in both sections. Otherwise, it will be dropped/destroyed in the section that it is not excluded from.

# Configure inventory rules here.
inventory:
  exclude: # List groups or individual items to exclude from dropping in the main inventory.
    - Swords # Exclude all items in the "Swords" group.
    - Tier2Items # Exclude all items in the "Tier2Items" group.
    - Bows # Exclude all items in the "Bows" group.
  includeOverride: # List groups or individual items to always drop in the main inventory, even if they are listed in the exclude section of the inventory.
    - BowFineWood # Always drop the item "BowFineWood" in the main inventory.
    - Wood # Always drop the item "Wood" in the main inventory.
  #destroy: # List groups or individual items to destroy instead of dropping in the main inventory.
    #- Arrows # Destroy the item "Arrows" instead of dropping it in the main inventory.
    #- Scraps # Destroy the item "Scraps" instead of dropping it in the main inventory.

# Configure hotbar rules here.
hotbar:
  exclude: # List groups or individual items to exclude from dropping in the hotbar.
    - Food # Exclude all items in the "Food" group.
    - PickaxeBronze # Exclude the item "PickaxeBronze" from the hotbar.
  includeOverride: # List groups or individual items to always drop in the hotbar, even if they are listed in the exclude section.
    - PickaxeBronze # Always drop the item "PickaxeBronze" in the hotbar.
  #destroy: # List groups or individual items to destroy instead of dropping in the hotbar.
    #- Arrows # Destroy the item "Arrows" instead of dropping it in the hotbar.
    #- Scraps # Destroy the item "Scraps" instead of dropping it in the hotbar.
