name: TrophyProwler_TW
clonePrefabName: TrophyProwler_TW
craftingStation: $piece_workbench
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- ProwlerFang_TW:10:1:True
