name: TrophyRottingElk_TW
clonePrefabName: TrophyRottingElk_TW
craftingStation: $piece_workbench
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- RottenPelt_TW:10:1:True
