name: TrophyGjall
clonePrefabName: TrophyGjall
craftingStation: $piece_workbench
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- Bilebag:5:1:True
