name: TrophySeekerBrute
clonePrefabName: TrophySeekerBrute
craftingStation: $piece_workbench
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- Mandible:10:1:True
