name: TrophyHatchling
clonePrefabName: TrophyHatchling
craftingStation: $piece_workbench
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- FreezeGland:15:1:True
