name: ChoppedVeggies_warp
clonePrefabName: ChoppedVeggies_warp
craftingStation: $piece_preptable
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 2
disabled: false
requireOnlyOneIngredient: false
reqs:
- Carrot:1:1:True
- Turnip:1:1:True
- Onion:1:1:True
