name: FlambeedWolfStrips_warp
clonePrefabName: FlambeedWolfStrips_warp
craftingStation: $piece_preptable
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 2
disabled: false
requireOnlyOneIngredient: false
reqs:
- WolfMeat:2:1:True
- MeadTasty:1:1:True
- Blueberries:4:1:True
