- prefab: instanced_swamp_grass
  amount: 2
  biome: RockyCoast
  instanced: true
  scaleMin: 1.35
  maxTilt: 25
  minAltitude: 0
  maxAltitude: 1000
  terrainTilt: true
  fractalThresholdMin: 0.5
- prefab: instanced_forest_groundcover_brown
  amount: 2
  biome: RockyCoast
  instanced: true
  scaleMin: 0.75
  scaleMax: 1
  maxTilt: 25
  minAltitude: 0
  maxAltitude: 1000
  terrainTilt: true
  fractalThresholdMin: 0.5
- prefab: instanced_swamp_ormbunke
  amount: 2
  biome: RockyCoast
  instanced: true
  scaleMin: 0.5
  scaleMax: 0.75
  maxTilt: 25
  minAltitude: 0
  maxAltitude: 1000
  terrainTilt: true
  fractalThresholdMin: 0.5
- prefab: instanced_small_rock1
  amount: 15
  biome: RockyCoast
  instanced: true
  onUncleared: false
  onCleared: true
  scaleMax: 2
  maxTilt: 45
  minAltitude: 0
  maxAltitude: 1000
  terrainTilt: true
  fractalThresholdMax: 0
- prefab: instanced_vass
  amount: 20
  biome: RockyCoast
  instanced: true
  scaleMax: 1.3
  maxTilt: 90
  minAltitude: -1
  maxAltitude: -0.1
  snapToWater: true
  fractalScale: 1.5