- prefab: VF_wild_shrine_green1
  biome: Meadows
  quantity: 100
  minAltitude: 1
  minDistanceFromSimilar: 1000
  slopeRotation: true
  maxTerrainDelta: 2
  exteriorRadius: 5
  clearArea: true
  noBuild: true
- prefab: VF_wild_shrine_blue1
  biome: BlackForest
  quantity: 100
  minAltitude: 1
  minDistanceFromSimilar: 1000
  slopeRotation: true
  maxTerrainDelta: 2
  exteriorRadius: 5
  clearArea: true
  noBuild: true
- prefab: VF_wild_shrine_green2
  biome: Swamp
  quantity: 100
  minAltitude: 1
  minDistanceFromSimilar: 1000
  slopeRotation: true
  maxTerrainDelta: 2
  exteriorRadius: 5
  clearArea: true
  noBuild: true
- prefab: VF_wild_shrine_blue2
  biome: Mountain
  quantity: 100
  minAltitude: 1
  minDistanceFromSimilar: 1000
  slopeRotation: true
  maxTerrainDelta: 2
  exteriorRadius: 5
  clearArea: true
  noBuild: true
- prefab: VF_wild_shrine_yellow1
  biome: Plains
  quantity: 100
  minAltitude: 1
  minDistanceFromSimilar: 1000
  slopeRotation: true
  maxTerrainDelta: 2
  exteriorRadius: 5
  clearArea: true
  noBuild: true
- prefab: VF_wild_shrine_purple1
  biome: Mistlands
  quantity: 100
  minAltitude: 1
  minDistanceFromSimilar: 1000
  slopeRotation: true
  maxTerrainDelta: 2
  exteriorRadius: 5
  clearArea: true
  noBuild: true
