- prefab: Serpent
  biome: RockyCoast
  spawnChance: 10
  maxSpawned: 1
  spawnInterval: 2000
  minLevel: 2
  maxLevel: 3
  minAltitude: -25
  maxAltitude: -20
  spawnAtDay: true
  spawnAtNight: true
  spawnDistance: 50
  groupSizeMin: 1
  groupSizeMax: 1
  groupRadius: 1
  overrideLevelupChance: 40
# - prefab: Dino1_coe
#   biome: RockyCoast
#   spawnChance: 50
#   maxSpawned: 3
#   spawnInterval: 480
#   minLevel: 1
#   maxLevel: 3
#   minAltitude: 0
#   maxAltitude: 20
#   spawnDistance: 15
#   groupSizeMin: 2
#   groupSizeMax: 3
#   groupRadius: 3
#   overrideLevelupChance: 35
# - prefab: Dino5_coe
#   biome: RockyCoast
#   spawnChance: 25
#   maxSpawned: 1
#   spawnInterval: 500
#   minLevel: 1
#   maxLevel: 2
#   minAltitude: 0
#   maxAltitude: 20
#   spawnDistance: 15
#   groupSizeMin: 1
#   groupSizeMax: 1
#   groupRadius: 2
#   overrideLevelupChance: 25
# - prefab: Dino17_coe
#   biome: RockyCoast
#   spawnChance: 35
#   maxSpawned: 3
#   spawnInterval: 480
#   maxLevel: 3
#   minAltitude: 0
#   maxAltitude: 20
#   spawnDistance: 15
#   groupSizeMin: 1
#   groupSizeMax: 3
#   groupRadius: 3
#   overrideLevelupChance: 50
# - prefab: Dino17_coe
#   biome: RockyCoast
#   spawnChance: 50
#   maxSpawned: 3
#   spawnInterval: 300
#   maxLevel: 3
#   minAltitude: -10
#   maxAltitude: 20
#   requiredEnvironments: Coast Heat
#   spawnDistance: 25
#   groupSizeMin: 1
#   groupSizeMax: 2
#   groupRadius: 10
#   groundOffset: 20
#   overrideLevelupChance: 35
# - prefab: Dino17_coe
#   biome: RockyCoast
#   spawnChance: 45
#   maxSpawned: 3
#   spawnInterval: 480
#   minLevel: 2
#   maxLevel: 3
#   minAltitude: 0
#   maxAltitude: 1
#   requiredEnvironments: Coast Rain, Coast Storm
#   spawnDistance: 50
#   groupSizeMin: 1
#   groupSizeMax: 2
#   groupRadius: 3
#   overrideLevelupChance: 40
# - prefab: Dino5_coe
#   biome: RockyCoast
#   spawnChance: 30
#   maxSpawned: 2
#   spawnInterval: 300
#   minLevel: 2
#   maxLevel: 3
#   minAltitude: 0
#   maxAltitude: 2
#   requiredEnvironments: Coast Rain, Coast Storm
#   spawnDistance: 15
#   groupSizeMin: 1
#   groupSizeMax: 1
#   groupRadius: 1
#   overrideLevelupChance: 35
- prefab: Seagal
  biome: RockyCoast
  spawnChance: 50
  maxSpawned: 5
  spawnInterval: 120
  minAltitude: -30
  maxAltitude: 5
  spawnDistance: 51
  groupSizeMax: 2
  groupRadius: 2
- prefab: Fish1
  biome: RockyCoast
  spawnChance: 50
  maxSpawned: 5
  spawnInterval: 120
  maxLevel: 5
  minAltitude: -3
  maxAltitude: -1.5
  spawnDistance: 20
  groupSizeMin: 2
  groupSizeMax: 6
  groupRadius: 2
  maxTilt: 99
  groundOffset: 0.1
  overrideLevelupChance: 20
- prefab: Fish2
  biome: RockyCoast
  spawnChance: 50
  maxSpawned: 4
  spawnInterval: 120
  maxLevel: 5
  minAltitude: -5
  maxAltitude: -2
  spawnDistance: 20
  groupSizeMin: 2
  groupSizeMax: 4
  groupRadius: 2
  maxTilt: 99
  groundOffset: 0.1
  overrideLevelupChance: 20
- prefab: Fish3
  biome: RockyCoast
  spawnChance: 50
  maxSpawned: 3
  spawnInterval: 120
  maxLevel: 5
  minAltitude: -999
  maxAltitude: -5
  spawnDistance: 20
  groupSizeMax: 2
  groupRadius: 2
  maxTilt: 99
  groundOffset: 0.1
  overrideLevelupChance: 20
- prefab: Fish5
  biome: RockyCoast
  spawnChance: 50
  maxSpawned: 10
  spawnInterval: 80
  maxLevel: 5
  minAltitude: -999
  maxAltitude: -5
  spawnDistance: 12
  groupSizeMin: 3
  groupSizeMax: 7
  groupRadius: 2
  maxTilt: 99
  groundOffset: 0.1
  overrideLevelupChance: 20
- prefab: Fish6
  biome: RockyCoast
  spawnChance: 60
  maxSpawned: 10
  spawnInterval: 80
  maxLevel: 5
  minAltitude: -999
  maxAltitude: -5
  spawnDistance: 10
  groupSizeMin: 3
  groupSizeMax: 7
  groupRadius: 2
  maxTilt: 99
  groundOffset: 0.1
  overrideLevelupChance: 20
- prefab: Fish7
  biome: RockyCoast
  spawnChance: 60
  maxSpawned: 7
  spawnInterval: 80
  maxLevel: 5
  minAltitude: -999
  maxAltitude: -5
  spawnDistance: 20
  groupSizeMin: 3
  groupSizeMax: 6
  groupRadius: 2
  maxTilt: 99
  groundOffset: 0.1
  overrideLevelupChance: 20
- prefab: Fish8
  biome: RockyCoast
  spawnChance: 50
  maxSpawned: 10
  spawnInterval: 80
  maxLevel: 5
  minAltitude: -999
  maxAltitude: -5
  spawnDistance: 12
  groupSizeMin: 2
  groupSizeMax: 7
  groupRadius: 2
  maxTilt: 99
  groundOffset: 0.1
  overrideLevelupChance: 20